version: 1.0.{build}
image: Visual Studio 2019
environment:
  matrix:
    - mutation-test: false
    - mutation-test: true
matrix:
  fast_finish: true
  allow_failures:
    - mutation-test: true
install:
  dotnet tool install --global dotnet-stryker --version 0.12.0
build:
  verbosity: minimal
build_script:
  dotnet build
test_script:
  dotnet test
after_test:
  - cd XUnitTestProject1
  - dotnet stryker -r "['html','dots']"
artifacts:
  - path: '**\mutation-report.html'